modify build and docker-compose.yaml

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,3 +1,15 @@
-docker build -t freepbx-docker-unimrcp:16.16 .  --build-arg UNIMRCP_USER=""  --build-arg UNIMRCP_PASS="" 
+#!/bin/bash
 
+# Load environment variables from .env file
+if [ -f .env ]; then
+  source .env
+else
+  echo "Error: .env file not found!"
+  exit 1
+fi
+TAG=16.16.2
+
+#docker build --no-cache -t freepbx-docker-unimrcp:$TAG .  --build-arg UNIMRCP_USER="${UNIMRCP_USER}"  --build-arg UNIMRCP_PASS="${UNIMRCP_PASS}"
+
+docker build -t freepbx-docker-unimrcp:$TAG .  --build-arg UNIMRCP_USER="${UNIMRCP_USER}"  --build-arg UNIMRCP_PASS="${UNIMRCP_PASS}"
 
